spring:
   application:
      name: monitor
#tomcat端口号
server:
   port: 9031
#自我保护机制
eureka:
   instance:
      hostname: 127.0.0.1
      port: 9999
   client:
      serviceUrl:
         defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/