spring:
   application:
      name: eureka
server:
   port: 9999
eureka:
   instance:
      hostname: 127.0.0.1
      prefer-ip-address: true
   client:
      registerWithEureka: false #表示是否将自己注册到Eureka Server，默认为true
      fetchRegistry: false #表示是否从Eureka Server获取注册信息，默认为true
      serviceUrl:
         defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/