spring:
   application:
      name: iam
   datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://120.77.253.118:3308/erp-iam?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
   redis:
      port: 6379
      host: 120.77.253.118
   jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
      serialization.write-dates-as-timestamps: false
#      password:
#tomcat端口号
server:
   port: 9021
swagger:
   enabled: true
   package: com.zhuoxun.it.iam
#自我保护机制
eureka:
   instance:
      hostname: 127.0.0.1
      port: 9999
   client:
      serviceUrl:
         defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
#mybatis扫描配置
mybatis:
   mapper-locations: classpath:mappers/*.xml
   type-aliases-package: com.zhuoxun.it.iam.entity
   configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
   helper-dialect: mysql
   reasonable: true
   support-methods-arguments: true
   params: count=countsql